services:
  brats_A:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-brats-a:latest
    volumes:
      - $BRATS_A_INPUT_PATH:/mnt/input/data
      - $BRATS_A_OUTPUT_PATH:/mnt/output/preprocessed
    command: ["python3", "preprocess_brats_A.py"]
  brats_B:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-brats-b:latest
    volumes:
      - $BRATS_B_INPUT_PATH:/mnt/input/data
      - $BRATS_B_OUTPUT_PATH:/mnt/output/preprocessed
    command: ["python3", "preprocess_brats_B.py"]
  brats_C:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-brats-c:latest
    volumes:
      - $BRATS_C_INPUT_PATH:/mnt/input/data
      - $BRATS_C_OUTPUT_PATH:/mnt/output/preprocessed
    command: ["python3", "preprocess_brats_C.py"]
  brats_D:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}preprocess-brats-d:latest
    volumes:
      - $BRATS_D_INPUT_PATH:/mnt/input/data
      - $BRATS_D_OUTPUT_PATH:/mnt/output/preprocessed
    command: ["python3", "preprocess_brats_D.py"]
