services:
  train:
    image: ${CONTAINER_REGISTRY:+$CONTAINER_REGISTRY/}depa-training:latest
    volumes:
      - $MEDQA_INPUT_PATH:/mnt/remote/medqa
      - $CHATDOCTOR_INPUT_PATH:/mnt/remote/chatdoctor
      - $MEDQUAD_INPUT_PATH:/mnt/remote/medquad
      - $MODEL_INPUT_PATH:/mnt/remote/model
      - $MODEL_OUTPUT_PATH:/mnt/remote/output
      - $CONFIGURATION_PATH:/mnt/remote/config
    command: ["/bin/bash", "run.sh"]